# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78abc36e73af8c14e20b9dd9d1e4a96d08791e5aa858ba99d9fd77be88dbd544f64b148ca76109f7ca6aa144d9ffce1d40969c8f93938adb672a98d67e6750e7

test:
  secret_key_base: 6a78687c873367f27b9d449295b7b773fe879feb9129acaa7b8f1d98e887ac9e53d00072ef144ac783542e45c915707c52aeab4733015ca086b2255af0e2d9f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
